import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { COLOR_THEME_COOKIE_NAME } from "@/utils/constants";
import { DARK_TOKENS, LIGHT_TOKENS } from "@/utils/colors";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const savedTheme = (await cookies()).get(COLOR_THEME_COOKIE_NAME);
  const theme = savedTheme?.value ?? 'light';

  return (
    <html lang="en" data-color-theme={theme} style={theme === 'light' ? LIGHT_TOKENS : DARK_TOKENS}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
